ALTER TABLE `settings` CHANGE `pricelist_thumb_width` `pricelist_thumb_width` INT( 3 ) NULL DEFAULT NULL ;
ALTER TABLE `settings` CHANGE `pricelist_thumb_height` `pricelist_thumb_height` INT( 3 ) NULL DEFAULT NULL ;
ALTER TABLE `settings` CHANGE `category_thumb_width` `category_thumb_width` INT( 3 ) NULL DEFAULT NULL ;
ALTER TABLE `settings` CHANGE `category_thumb_height` `category_thumb_height` INT( 3 ) NULL DEFAULT NULL ;
ALTER TABLE `settings` CHANGE `background` `pricelist_orderby` TINYINT( 1 ) NULL DEFAULT NULL ;
ALTER TABLE `settings` CHANGE `sales_mail` `sales_mail` varchar(500) default NULL ;
ALTER TABLE `settings` CHANGE `webmaster_mail` `webmaster_mail` varchar(500) default NULL ;
ALTER TABLE `settings` CHANGE `shipping_postal` `autosubmit` TINYINT( 1 ) NULL DEFAULT NULL ;
ALTER TABLE `settings` CHANGE `shipping_atstore` `create_pdf` TINYINT( 1 ) NULL DEFAULT NULL ;
UPDATE `settings` SET `pricelist_orderby` = 2 ;
UPDATE `settings` SET `autosubmit` = 0 ;
UPDATE `settings` SET `create_pdf` = 1 ;