-- correction of issue in apps where db files are not loaded in correct order, fixed in apps 0.8
REPLACE INTO `##faces` (`ID`, `NAME`, `ELEMENTCOUNT`, `DATA`, `TYPE`, `ENTITY`, `LABEL`) VALUES(49, 'taxes', 2, '{"3":{"subelements":{"1":{"id":1,"populate":"","sortorder":1}},"rules":[],"mandatory":1,"links":[],"id":3,"label":"Label       ","x":45,"y":5,"type":"text_small","column":"LABEL","children":2},"5":{"subelements":{"1":{"id":1,"populate":"1","sortorder":2}},"rules":[],"links":[],"id":5,"label":"Cascading        ","x":45,"y":44,"type":"checkbox","column":"CASCADING","children":2}}', 'DB', 'taxes', 'Taxes');
REPLACE INTO `##faces` (`ID`, `NAME`, `ELEMENTCOUNT`, `DATA`, `TYPE`, `ENTITY`, `LABEL`) VALUES(50, 'taxrates', 4, '{"4":{"subelements":{"1":{"id":1,"populate":"9","sortorder":1,"hide":1},"2":{"id":2,"populate":"id","label":"Key"},"3":{"id":3,"populate":"label","label":"Value"},"4":{"id":4,"populate":"taxes","label":"Table"}},"rules":[],"links":[],"id":4,"label":"Taxes ID  ","x":45,"y":5,"type":"sql","column":"TAXESID","children":5},"1":{"subelements":{"1":{"id":1,"populate":"","sortorder":3}},"rules":[],"links":[],"id":1,"label":"Country    ","x":45,"y":52,"type":"country","column":"COUNTRY","children":2},"2":{"subelements":{"1":{"id":1,"populate":"","sortorder":2}},"rules":[],"links":[],"id":2,"label":"State   ","x":45,"y":90,"type":"text_large","column":"STATE","children":2},"3":{"subelements":{"1":{"id":1,"populate":"","sortorder":4}},"rules":[],"mandatory":1,"links":[],"id":3,"label":"Rate   ","x":45,"y":129,"type":"percentage","column":"RATE","children":2}}', 'DB', 'taxrates', 'Tax rates');
REPLACE INTO `##faces` (`ID`, `NAME`, `ELEMENTCOUNT`, `DATA`, `TYPE`, `ENTITY`, `LABEL`) VALUES(51, 'settings', 2, '{"1":{"subelements":{"1":{"id":1,"populate":"1"}},"rules":[],"links":[],"id":1,"label":"Activate fast checkout  ","x":45,"y":5,"type":"checkbox","column":"FASTCHECKOUT","children":2},"2":{"subelements":{"1":{"id":1,"populate":"1"}},"rules":[],"links":[],"id":2,"label":"Date of birth on registration form ","x":45,"y":44,"type":"checkbox","column":"REGISTERDOB","children":2}}', 'DB', 'settings', 'Settings');
REPLACE INTO `##flink` (`ID`, `DATE_CREATED`, `DATE_UPDATED`, `FORMIN`, `FORMOUT`, `ACTION`, `ICON`, `DISPLAYIN`, `MAPPING`, `FORMOUTALT`, `REDIRECT`, `ACTIONIN`, `ACTIONOUT`, `DISPLAYOUT`) VALUES(10, '0000-00-00 00:00:00', NULL, 49, 49, 'edit', 'edit.png', 'list', NULL, NULL, NULL, NULL, 'edit', 'form');
REPLACE INTO `##flink` (`ID`, `DATE_CREATED`, `DATE_UPDATED`, `FORMIN`, `FORMOUT`, `ACTION`, `ICON`, `DISPLAYIN`, `MAPPING`, `FORMOUTALT`, `REDIRECT`, `ACTIONIN`, `ACTIONOUT`, `DISPLAYOUT`) VALUES(11, '0000-00-00 00:00:00', NULL, 49, 49, 'delete', 'delete.png', 'list', NULL, NULL, NULL, NULL, 'delete', 'form');
REPLACE INTO `##flink` (`ID`, `DATE_CREATED`, `DATE_UPDATED`, `FORMIN`, `FORMOUT`, `ACTION`, `ICON`, `DISPLAYIN`, `MAPPING`, `FORMOUTALT`, `REDIRECT`, `ACTIONIN`, `ACTIONOUT`, `DISPLAYOUT`) VALUES(12, '0000-00-00 00:00:00', NULL, 49, 49, 'view', 'view.png', 'list', NULL, NULL, NULL, NULL, 'view', 'form');
REPLACE INTO `##flink` (`ID`, `DATE_CREATED`, `DATE_UPDATED`, `FORMIN`, `FORMOUT`, `ACTION`, `ICON`, `DISPLAYIN`, `MAPPING`, `FORMOUTALT`, `REDIRECT`, `ACTIONIN`, `ACTIONOUT`, `DISPLAYOUT`) VALUES(13, '2010-02-12 12:56:59', NULL, 49, 50, 'Rates', '', 'list', 'taxesid:id', '', '', NULL, '', 'list');
REPLACE INTO `##flink` (`ID`, `DATE_CREATED`, `DATE_UPDATED`, `FORMIN`, `FORMOUT`, `ACTION`, `ICON`, `DISPLAYIN`, `MAPPING`, `FORMOUTALT`, `REDIRECT`, `ACTIONIN`, `ACTIONOUT`, `DISPLAYOUT`) VALUES(14, '0000-00-00 00:00:00', NULL, 50, 50, 'edit', 'edit.png', 'list', NULL, NULL, NULL, NULL, 'edit', 'form');
REPLACE INTO `##flink` (`ID`, `DATE_CREATED`, `DATE_UPDATED`, `FORMIN`, `FORMOUT`, `ACTION`, `ICON`, `DISPLAYIN`, `MAPPING`, `FORMOUTALT`, `REDIRECT`, `ACTIONIN`, `ACTIONOUT`, `DISPLAYOUT`) VALUES(15, '0000-00-00 00:00:00', NULL, 50, 50, 'delete', 'delete.png', 'list', NULL, NULL, NULL, NULL, 'delete', 'form');
REPLACE INTO `##flink` (`ID`, `DATE_CREATED`, `DATE_UPDATED`, `FORMIN`, `FORMOUT`, `ACTION`, `ICON`, `DISPLAYIN`, `MAPPING`, `FORMOUTALT`, `REDIRECT`, `ACTIONIN`, `ACTIONOUT`, `DISPLAYOUT`) VALUES(16, '0000-00-00 00:00:00', NULL, 50, 50, 'view', 'view.png', 'list', NULL, NULL, NULL, NULL, 'view', 'form');
REPLACE INTO `##flink` (`ID`, `DATE_CREATED`, `DATE_UPDATED`, `FORMIN`, `FORMOUT`, `ACTION`, `ICON`, `DISPLAYIN`, `MAPPING`, `FORMOUTALT`, `REDIRECT`, `ACTIONIN`, `ACTIONOUT`, `DISPLAYOUT`) VALUES(17, '0000-00-00 00:00:00', NULL, 51, 51, 'edit', 'edit.png', 'list', NULL, NULL, NULL, NULL, 'edit', 'form');
REPLACE INTO `##flink` (`ID`, `DATE_CREATED`, `DATE_UPDATED`, `FORMIN`, `FORMOUT`, `ACTION`, `ICON`, `DISPLAYIN`, `MAPPING`, `FORMOUTALT`, `REDIRECT`, `ACTIONIN`, `ACTIONOUT`, `DISPLAYOUT`) VALUES(18, '0000-00-00 00:00:00', NULL, 51, 51, 'delete', 'delete.png', 'list', NULL, NULL, NULL, NULL, 'delete', 'form');
REPLACE INTO `##flink` (`ID`, `DATE_CREATED`, `DATE_UPDATED`, `FORMIN`, `FORMOUT`, `ACTION`, `ICON`, `DISPLAYIN`, `MAPPING`, `FORMOUTALT`, `REDIRECT`, `ACTIONIN`, `ACTIONOUT`, `DISPLAYOUT`) VALUES(19, '0000-00-00 00:00:00', NULL, 51, 51, 'view', 'view.png', 'list', NULL, NULL, NULL, NULL, 'view', 'form');